name: basic  
on: [push]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get update && sudo apt-get install -y cmake
            - run: mkdir build && cmake -B build -S. -G "MinGW Makefiles" && cmake --build build
            - run: ./main 4 6